# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3, 5)

In [3]:
print(A, '\n')
print(A.ndim, '\n')
print(A.shape, '\n')
print(A.size, '\n')
print(type(A))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

2 

(3, 5) 

15 

<class 'numpy.ndarray'>


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [6]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [26]:
print(B - C, '\n')
print(B * C, '\n')
print(B @ C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]] 

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]] 

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [27]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
# Exponentiate each number elementwise
B_exp = np.exp(B)
print(B_exp, '\n')

# Calculate the minimum value in the whole matrix
min_value_matrix = np.min(B)
print(min_value_matrix, '\n')

# Calculate the minimum vlaue in each row
min_value_rows = np.min(B, axis=1)
print(min_value_rows, '\n')

# Calculate the minimum vlaue in each column
min_value_columns = np.min(B, axis=0)
print(min_value_columns, '\n')

# Find the index for the minimum value in the whole matrix
min_index_matrix = np.argmin(B)
print(min_index_matrix, '\n')

# Find the index for the minimum value in each row
min_index_rows = np.argmin(B, axis=1)
print(min_index_rows, '\n')

# Calulcate the sum of all elements in the matrix
sum_all_elements = np.sum(B)
print(sum_all_elements, '\n')

# Calulcate the mean of each column
mean_each_column = np.mean(B, axis=0)
print(mean_each_column, '\n')

# Calulcate the median for each column
median_each_column = np.median(B, axis=0)
print(median_each_column, '\n')


[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]] 

1 

[1 4 7] 

[1 2 3] 

0 

[0 0 0] 

45 

[4. 5. 6.] 

[4. 5. 6.] 



### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [28]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [29]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

If you provide fewer indices than the number of dimensions (axes), NumPy will implicitly take all values along the remaining axes. 
In the above example only the first axis (axis=0) is specified and NumPy assumes : (i.e, take all elements) for that axis. Its called implicit slicing.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [57]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [66]:
for i in A:
    print(i)



[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
3


In [63]:
# Iterate element-wise using np.nditer (most efficent for higher N-D arrays)
for element in np.nditer(A):
    print(element)

# Iterate element-wise using the flat iterator, flats the array as if its a 1D array.
for element in A.flat:
    print(element)

# Iterate element-wise using nested loops, manual control but less time efficient.
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        print(A[i, j])


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [69]:
a = np.arange(30) # creates an array ranging from number 0 to 29. 
b = a.reshape((2, 3, -1)) # reshapes the array of a into three dimensions, [depth/slice = 3, rows = 3, columns = -1]. 
print(a)
print()

print(b)
print()
print(b.ndim) # This gives the number of axes (dimensions) of the array. In this case it return the value 3, i.e. its a 3D-array.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]

3


The above code first creates an 1D array containing a sequence of numbers from 0 to 29 (30 elements in total). 
It then reshapes the array into a 3D array using the reshape() function. The argument(2, 3, -1) specifices the shape:
* 2 means the depth or number of layers/slices along the first axis.
* 3 means that each layer is specified to have 3 rows
* -1 infer the appropriate size for the column dimension based on the number of elements in array a divided by the size of the other dimensions

In this case: **a** = 30 (elements), depth x rows = 2x3. NumPy then calculates that the third dimension ((30/2x3) = 5) must have 5 elements.
This means that the reshaped array **b** will have the shape (2, 3, 5):
* 2 layers(slices)
* Each layer has 3 rows
* Each row has 5 columns

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [70]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [71]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [73]:
A = np.arange(1, 5).reshape(2,2)
print(A)
print()

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]

[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [3]:
from typing import Union

def add_mult_matrices(matrix_a: np.ndarray, matrix_b: np.ndarray, operation: str) -> Union[np.ndarray, None]:
    # Validate that both inputs are numpy.ndarrays
    if not isinstance(matrix_a, np.ndarray):
        raise ValueError('The input must be a numpy.ndarray')
    if not isinstance(matrix_b, np.ndarray):
        raise ValueError('The input must be a numpy.ndarray')
    
    # Check the operation type
    if operation == 'add':
        # Validate that the matrices have the same dimensions/shape
        if matrix_a.shape != matrix_b.shape:
            raise ValueError('Matrices must have the same dimensions for addition')
        return matrix_a + matrix_b
    elif operation == 'multiply':
        # Validates that the size conforms for matrix multiplication
        if matrix_a.shape[1] != matrix_b.shape[0]:
            raise ValueError('Number of columns in the first matrix must equal the number of rows in the second matrix')
        return matrix_a @ matrix_b 
    else:
        raise ValueError("Operation must be either 'add' or 'multiply")


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [7]:
# (a)
x = np.array([4, 3]) #shape is (2,)

# (b)
solution_b = 5 * x
print(solution_b)

# (c)
solution_c = 3 * x
print(solution_c)

# (d)
solution_d = 5 * x + 3 * x
print(solution_d)

# (f)
solution_f = 4 * x - x
print(solution_f)

# (g)
solution_g = np.atleast_2d(x).T # To convert a 1D array into a 2D column vector, an addiitional dimension must be added (1, 2). 
print(solution_g)
print()

# (h)
solution_h = x * np.atleast_2d(x).T # This is an example when NumPy uses broadcasting to perfom element-wise operations on arrays of different shapes.
print(solution_h)

# (i)
x_norm = np.linalg.norm(x)
print(x_norm)

# (k)

[20 15]
[12  9]
[32 24]
[12  9]
[[4]
 [3]]

[[16 12]
 [12  9]]
5.0


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [5]:
# Exercises 10.2.1
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4],[4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])

# (a)
solution_a = 2 * A
print('2A = ','\n', solution_a, '\n')

# (b)
solution_b = B - 2 * A
print('B - 2A = ', '\n', solution_b, '\n')

# (c)
solution_c = 3 * C - 2 * E
print('3C - 2E = ', '\n', solution_c, '\n')

# (d)
solution_d = 2 * D - 3 * C
print('2D - 3C = ', '\n', solution_d, '\n')

# (e)

solution_e = add_mult_matrices(D.T, 2 * D, 'add')
print('Transposed D + 2D = ', '\n', solution_e, '\n')

# (f)
solution_f = 2 * C.T - 2 * D.T
print('2C.transposed - 2D.transposed = ', '\n', solution_f, '\n')

# (g)
#solution_g = A.T - B # Not definied, operands could not broadcast together,
#print('A.transposed - B = ', '\n', solution_g, '\n')

# (h)
#solution_h = add_mult_matrices(A, C, 'multiply') # Raises ValueError because the matrices are undefinied

# (i)
solution_i = add_mult_matrices(C, D, 'multiply')
print('CD = ', '\n', solution_i, '\n')

# (j)
solution_j = add_mult_matrices(C, B, 'multiply')
print('CB = ', '\n', solution_j, '\n')

# (k)
solution_k = add_mult_matrices(C, I, 'multiply')
print('CI = ','\n', solution_k, '\n')

# (l)
solution_l = add_mult_matrices(A, B.T, 'multiply')
print('AB.T = ', '\n', solution_l, '\n')


2A =  
 [[ 4  2 -2]
 [ 2 -2  2]] 

B - 2A =  
 [[ 0 -4  3]
 [ 0 -2 -4]] 

3C - 2E =  
 [[ 1  4]
 [ 2 -1]] 

2D - 3C =  
 [[3 2]
 [2 3]] 

Transposed D + 2D =  
 [[ 9 12]
 [12  9]] 

2C.transposed - 2D.transposed =  
 [[-4 -4]
 [-4 -4]] 

CD =  
 [[11 10]
 [10 11]] 

CB =  
 [[  8 -10  -3]
 [ 10  -8   0]] 

CI =  
 [[1 2]
 [2 1]] 

AB.T =  
 [[5 2]
 [7 4]] 



In [8]:
# Exercise 10.2.2
A = np.array([[2, 3, 4], [5, 4, 1]])

# Calculate AA.transposed
solution = add_mult_matrices(A, A.T, 'multiply')
print('AA.T = ', '\n', solution)

AA.T =  
 [[29 26]
 [26 42]]


In [15]:
# Exerscise 10.2.3
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

# Verify that AB = AC and that B != C
AB = add_mult_matrices(A, B, 'multiply')
AC = add_mult_matrices(A, C, 'multiply')

# Checks if all elements of two arrays are equal.
if np.all(AB == AC):
    print('AB = AC ', '\n', AB,'\n')
else:
    print('The arrays are not equal ')
    
# Checks if B is equal to C
if np.all(B == C):
    print('B equals C')
else:
    print('B is not equal to C')

AB = AC  
 [[ 4  7]
 [ 8 14]] 

B is not equal to C


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [35]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


: 

In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)